
SET CURRENT SCHEMA REPO;

CREATE OR REPLACE FUNCTION UDF_BASE64_DECODE(IN s CLOB(8 M))
    RETURNS BLOB(5 M)
    LANGUAGE JAVA
    PARAMETER STYLE JAVA
    DETERMINISTIC
    NO SQL
    RETURNS NULL ON NULL INPUT
    FENCED THREADSAFE
    EXTERNAL NAME 'IPTO_JAR:org.gautelis.repo.udpf.B64.decode';


CREATE OR REPLACE PROCEDURE INGEST_NEW_UNIT_JSON (
    IN  p_unit     CLOB(2M),
    OUT p_unitid   BIGINT,
    OUT p_unitver  INTEGER,
    OUT p_created  TIMESTAMP,
    OUT p_modified TIMESTAMP
)
    EXTERNAL NAME 'IPTO_JAR:org.gautelis.repo.udpf.Routines.ingestNewUnit'
    LANGUAGE JAVA
    PARAMETER STYLE JAVA
    NO DBINFO
    FENCED
    MODIFIES SQL DATA;


CREATE OR REPLACE PROCEDURE INGEST_NEW_VERSION_JSON (
   IN  P_UNIT     CLOB(2M),
   OUT P_UNITVER  INTEGER,
   OUT P_MODIFIED TIMESTAMP
)
    EXTERNAL NAME 'IPTO_JAR:org.gautelis.repo.udpf.Routines.ingestNewVersion'
    LANGUAGE JAVA
    PARAMETER STYLE JAVA
    NO DBINFO
    FENCED
    MODIFIES SQL DATA;



